apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "log-platform.fullname" . }}-ingestion
  labels:
    {{- include "log-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingestion
spec:
  replicas: {{ .Values.replicaCount.ingestion }}
  selector:
    matchLabels:
      {{- include "log-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ingestion
  template:
    metadata:
      labels:
        {{- include "log-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ingestion
    spec:
      containers:
      - name: log-ingestion
        image: "{{ .Values.image.repository }}/log-ingestion:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8000
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: {{ .Values.kafka.bootstrapServers }}
        - name: REDIS_HOST
          value: {{ .Values.redis.host }}
        resources:
          {{- toYaml .Values.resources.ingestion | nindent 12 }}
