apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ingress.yaml
  - deployments/log-ingestion.yaml
  - deployments/log-processor.yaml
  - deployments/log-query.yaml
  - deployments/frontend.yaml
  - services/services.yaml
  - configmaps/config.yaml
  - rbac/rbac.yaml
  - hpa/hpa.yaml
  - pdb/pdb.yaml
  - networkpolicies/netpol.yaml
