apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "log-analytics.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "log-analytics.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "log-analytics.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
