apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: log-analytics
  labels:
    app: log-analytics
spec:
  selector:
    matchLabels:
      app: api-gateway
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
