apiVersion: v2
name: log-system
description: Production-grade log aggregation system
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - logging
  - kubernetes
  - microservices
maintainers:
  - name: Platform Team
    email: platform@example.com
