apiVersion: v1
kind: Namespace
metadata:
  name: secrets-platform
  labels:
    name: secrets-platform
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: secrets-platform-prod
  labels:
    name: secrets-platform-prod
    istio-injection: enabled
    pod-security.kubernetes.io/enforce: baseline
