---
apiVersion: v1
kind: Namespace
metadata:
  name: ci-cd
  labels:
    purpose: continuous-deployment
    security: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    environment: production
    security: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    environment: staging
    security: restricted
