apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: log-processing

resources:
  - namespace.yaml
  - redis.yaml
  - postgres.yaml
  - ingestion-api.yaml
  - analytics-engine.yaml
  - dashboard.yaml
  - network-policy.yaml
  - ../rbac/serviceaccount.yaml

commonLabels:
  app.kubernetes.io/part-of: log-processing-system
  app.kubernetes.io/managed-by: kustomize
