---
apiVersion: v1
kind: Namespace
metadata:
  name: analytics
  labels:
    name: analytics
    tier: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: devops
  labels:
    name: devops
    tier: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: developers
  labels:
    name: developers
    tier: application
---
apiVersion: v1
kind: Namespace
metadata:
  name: auditors
  labels:
    name: auditors
    tier: security
