{{- define "log-platform.labels" -}}
helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
region: {{ .Values.global.region }}
{{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-log-ingestion
  namespace: {{ .Release.Namespace }}
  labels:
    app: log-ingestion
    {{ include "log-platform.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.logIngestion.replicaCount }}
  selector:
    matchLabels:
      app: log-ingestion
  template:
    metadata:
      labels:
        app:     log-ingestion
        version: v1
        region:  {{ .Values.global.region }}
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: log-ingestion
      containers:
        - name: log-ingestion
          image: "{{ .Values.logIngestion.image.repository }}:{{ .Values.logIngestion.image.tag }}"
          imagePullPolicy: {{ .Values.logIngestion.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: REGION
              value: {{ .Values.global.region | quote }}
          resources: {{- toYaml .Values.logIngestion.resources | nindent 12 }}
          livenessProbe:
            httpGet: { path: /health/live, port: 8000 }
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet: { path: /health/ready, port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 10
---
{{- if .Values.logIngestion.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-log-ingestion-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-log-ingestion
  minReplicas: {{ .Values.logIngestion.hpa.minReplicas }}
  maxReplicas: {{ .Values.logIngestion.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.logIngestion.hpa.targetCPUPercent }}
{{- end }}
