apiVersion: v1
kind: Service
metadata:
  name: security-dashboard
  namespace: runtime-security
spec:
  selector:
    app: security-dashboard
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-dashboard
  namespace: runtime-security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-dashboard
  template:
    metadata:
      labels:
        app: security-dashboard
    spec:
      containers:
      - name: dashboard
        image: security-dashboard:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        env:
        - name: VITE_API_URL
          value: "http://security-event-processor-service:8000"
