name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-service, frontend, log-processor]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build ${{ matrix.service }}
      uses: docker/build-push-action@v4
      with:
        context: ./services/${{ matrix.service }}
        push: false
        tags: ${{ matrix.service }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Analyze image size
      run: |
        docker images ${{ matrix.service }}:${{ github.sha }} --format "table {{.Repository}}\t{{.Tag}}\t{{.Size}}"

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
    
    - name: Deploy to Kubernetes
      run: |
        echo "Deploy to production cluster"
        # kubectl apply -f k8s/base/
