{{- if .Values.logIngestor.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "log-tracing-system.fullname" . }}-ingestor
  namespace: app
  labels:
    {{- include "log-tracing-system.labels" . | nindent 4 }}
    app: log-ingestor
spec:
  replicas: {{ .Values.logIngestor.replicaCount }}
  selector:
    matchLabels:
      app: log-ingestor
  template:
    metadata:
      labels:
        app: log-ingestor
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      serviceAccountName: log-ingestor-sa
      containers:
        - name: log-ingestor
          image: "{{ .Values.global.imageRegistry }}{{ .Values.logIngestor.image.name }}:{{ .Values.logIngestor.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 8000
              name: http
          resources:
            {{- toYaml .Values.logIngestor.resources | nindent 12 }}
          livenessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet: { path: /ready, port: http }
            initialDelaySeconds: 3
            periodSeconds: 5
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
{{- end }}
