apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: global-log-platform
build:
  artifacts:
    - image: log-ingestion
      context: services/log-ingestion
      docker:
        dockerfile: Dockerfile
    - image: log-processor
      context: services/log-processor
      docker:
        dockerfile: Dockerfile
    - image: aggregator
      context: services/aggregator
      docker:
        dockerfile: Dockerfile
    - image: log-dashboard
      context: frontend
      docker:
        dockerfile: Dockerfile
  local:
    push: false
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: log-platform
        chartPath: helm/log-platform
        valuesFiles:
          - helm/log-platform/values.yaml
        setValues:
          global.region: local
  kubectl:
    manifests:
      - k8s/base/**/*.yaml
      - k8s/istio/*.yaml
portForward:
  - resourceType: service
    resourceName: log-ingestion
    namespace: log-processing
    port: 8000
    localPort: 8000
  - resourceType: service
    resourceName: aggregator
    namespace: log-processing
    port: 8001
    localPort: 8001
