apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-api
  namespace: log-platform
  labels:
    app: analytics-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-api
  template:
    metadata:
      labels:
        app: analytics-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8002"
    spec:
      serviceAccountName: log-platform-sa
      containers:
      - name: analytics-api
        image: analytics-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002
        env:
        - name: REDIS_HOST
          value: "redis"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 10
          periodSeconds: 5
