apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: log-ingestion-api-dr
  namespace: log-processing
spec:
  host: log-ingestion-api
  trafficPolicy:
    loadBalancer:
      simple: LEAST_REQUEST
    outlierDetection:
      consecutiveErrors: 5
      interval: 30s
      baseEjectionTime: 30s
