apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: log-processor-vpa
  namespace: log-processing
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: log-processor
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: log-processor
        minAllowed:
          cpu:    "100m"
          memory: "128Mi"
        maxAllowed:
          cpu:    "2000m"
          memory: "2Gi"
