apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    name: frontend
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
  labels:
    name: backend
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-layer
  labels:
    name: data-layer
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
