apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    name: database
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: services
  labels:
    name: services
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
