apiVersion: v1
kind: Namespace
metadata:
  name: runtime-security
  labels:
    name: runtime-security
    security-monitoring: enabled
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
