{{- if .Values.ingestionApi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "log-analytics.fullname" . }}-ingestion-api
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.ingestionApi.replicaCount }}
  selector:
    matchLabels:
      app: ingestion-api
  template:
    metadata:
      labels:
        app: ingestion-api
        version: v1
    spec:
      containers:
      - name: ingestion-api
        image: "{{ .Values.ingestionApi.image.repository }}:{{ .Values.ingestionApi.image.tag }}"
        imagePullPolicy: {{ .Values.ingestionApi.image.pullPolicy }}
        resources:
{{ toYaml .Values.ingestionApi.resources | indent 10 }}
{{- end }}
