apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.webhook.generic: |
    url: http://event-processor.gitops-apps-prod/webhook/argocd
    headers:
    - name: Content-Type
      value: application/json
  
  trigger.on-sync-succeeded: |
    - when: app.status.operationState.phase in ['Succeeded']
      send: [sync-success]
  
  trigger.on-sync-failed: |
    - when: app.status.operationState.phase in ['Failed', 'Error']
      send: [sync-failure]
  
  template.sync-success: |
    webhook:
      generic:
        method: POST
        body: |
          {
            "type": "sync-succeeded",
            "metadata": {{toJson .app.metadata}},
            "status": {{toJson .app.status}}
          }
  
  template.sync-failure: |
    webhook:
      generic:
        method: POST
        body: |
          {
            "type": "sync-failed",
            "metadata": {{toJson .app.metadata}},
            "status": {{toJson .app.status}}
          }
