#!/bin/bash
# cleanup.sh - Stop containers, remove unused Docker resources, and project artifacts
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLATFORM_DIR="$SCRIPT_DIR/k8s-log-processing-platform"

echo "🧹 Cleanup: stopping services and removing Docker resources..."

# 1. Stop Docker Compose (log platform)
if [ -f "$PLATFORM_DIR/docker-compose.yml" ]; then
  (cd "$PLATFORM_DIR" && docker compose down -v 2>/dev/null) || true
fi

# 2. Stop any remaining running containers
docker stop $(docker ps -q) 2>/dev/null || true

# 3. Remove project artifacts (node_modules, venv, .pytest_cache, .pyc, __pycache__)
echo "   Removing node_modules, venv, .pytest_cache, __pycache__, .pyc..."
find "$SCRIPT_DIR" -type d -name "node_modules" -exec rm -rf {} + 2>/dev/null || true
find "$SCRIPT_DIR" -type d -name "venv" -exec rm -rf {} + 2>/dev/null || true
find "$SCRIPT_DIR" -type d -name ".pytest_cache" -exec rm -rf {} + 2>/dev/null || true
find "$SCRIPT_DIR" -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
find "$SCRIPT_DIR" -name "*.pyc" -delete 2>/dev/null || true

# 4. Remove Istio directory from generated platform (optional; regenerated by setup.sh)
if [ -d "$PLATFORM_DIR/istio" ]; then
  rm -rf "$PLATFORM_DIR/istio"
  echo "   Removed $PLATFORM_DIR/istio"
fi

# 5. Docker prune - remove unused containers, networks, images, volumes
echo "   Pruning Docker..."
docker container prune -f
docker network prune -f
docker image prune -af
docker volume prune -f

echo "✅ Cleanup complete!"
