apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: log-analytics

resources:
  - namespace.yaml
  - infrastructure.yaml
  - log-collector.yaml
  - log-processor.yaml
  - analytics-api.yaml
  - frontend.yaml
  - pdb.yaml
  - hpa.yaml
