apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: log-analytics
  labels:
    app: frontend
    service: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
    protocol: TCP
    name: http
  selector:
    app: frontend
