apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: log-platform
type: Opaque
stringData:
  connection-string: "postgresql+asyncpg://postgres:SecurePassword123!@postgresql.log-platform.svc.cluster.local:5432/logs"
  password: "SecurePassword123!"
