apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
    - name: http
      port: 8002
      targetPort: http
