apiVersion: v1
kind: Service
metadata:
  name: log-processor
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: log-processor
  ports:
    - name: http
      port: 8001
      targetPort: http
