apiVersion: v1
kind: Service
metadata:
  name: log-ingestion
  namespace: log-processing
  labels:
    app: log-ingestion
spec:
  selector:
    app: log-ingestion
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
