---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: log-ingestor-monitor
  namespace: observability
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames: ["app"]
  selector:
    matchLabels:
      app: log-ingestor
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: log-processor-monitor
  namespace: observability
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames: ["app"]
  selector:
    matchLabels:
      app: log-processor
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: analytics-monitor
  namespace: observability
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames: ["app"]
  selector:
    matchLabels:
      app: analytics-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
