apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payment-service-monitor
  namespace: ecommerce
  labels:
    app: payment-service
    release: prometheus
spec:
  selector:
    matchLabels:
      app: payment-service
  endpoints:
  - port: http
    interval: 15s
    path: /metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - ecommerce
