# Default values for rbac-platform

replicaCount:
  logProcessor: 2
  analyticsApi: 2
  auditService: 1
  rbacValidator: 1
  frontend: 2

image:
  pullPolicy: IfNotPresent

resources:
  logProcessor:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  analyticsApi:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  auditService:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
  rbacValidator:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
  frontend:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

service:
  type: LoadBalancer
  port: 80

namespaces:
  - analytics
  - devops
  - developers
  - auditors

rbac:
  enabled: true
  createServiceAccounts: true
  createRoles: true
  createClusterRoles: true

networkPolicy:
  enabled: true

monitoring:
  enabled: true
  prometheus:
    enabled: true
  grafana:
    enabled: true
